### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by nekklo** [spheenik/clarity-analyzer#2]
When trying to execute the mvn package command, I'm receiving the below error: 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
1:compile (default-compile) on project clarity-analyzer: Fatal error compiling:
invalid target release: 1.8 -> [Help 1]
```

Anyone can help on this please? Thanks

**Comment by spheenik** [comment]
looks like you're compiling it with a version of Java less than 8.
You need to have a pretty new JDK for this, around 8u40 or more...

**Comment by nekklo** [comment]
Should have googled this before xD, thanks for the help though :)
